<div id="contentProjectTeaser" class="row">
    <div class="small-12 columns">
        <?php if (!$this->sidebarProjects->isEmpty()): ?>
        <ul class="orbit" data-orbit>
            <?php if ($this->sidebarProjects): ?>
                <?php foreach($this->sidebarProjects as $project): ?>
                    <?php $projectDetails = $project->getProjectDetails()->getFirst() ?>
                    <li>
                        <div class="panel">
                            <div class="orbit-slide-data">
                                <?= $this->partial('partials/project.attribs.phtml', array('project' => $project, 'projectDetails' => $projectDetails)) ?>
                            </div>
                            <div class="orbit-caption"><?= $projectDetails->getLabel() ?></div>
                        </div>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <?= $this->translate('requested project could not be found.') ?>
            <?php endif; ?>
        </ul>
        <?php endif ?>
    </div>
</div>
