<?php $projectDetails = $project->getProjectDetails()->getFirst() ?>
<div id="sidebarProject" class="sidebar">
    <div class="slideStack">
        <h2><?= $this->translate('project details') ?></h2>
        <div class="slideElem">
            <img src="<?php echo '/images/project/' . $this->image(array('src' => BASE_PATH . '/public/images/project/' . $project->getImg(), 'x' => 265)) ?>" alt="<?= $projectDetails->getLabel() ?>"/>
        </div>
    </div>
</div>