<div id="projectList">
    <h2><?= $this->translate('projects list') ?></h2>
    <div id="accordionHorizontal" class="panel">
        <div class="hSlide active">
        <?php
            $n = 0;
            $p = 1;
            $pages = array(0);
        ?>
        <?php foreach($this->project as $project): ?>

            <?php if ($n > 0 && $n%5 == 0): ?>
                <?php array_push($pages, $p++); ?>
                </div><div class="hSlide">
            <?php endif ?>
            <?php $n++ ?>
            <section class="listElem">
                <?php $projectDetails = $project->getProjectDetails()->getFirst() ?>
                <div class="panelHeader">
                    <a class="more" href="<?= $this->url('project', array('action' => 'detail', 'id' => $project->getId())) ?>"><?= $this->translate('view details') ?></a>
                    <h3><?= $projectDetails->getLabel() ?></h3>
                </div>
                <div class="panelBody">
                    <div class="contact">
                        <?php $client = $project->getContactRelatedByFkContactClientId() ?>
                        <?php if (!empty($client)): ?>
                        <dl class="client attrib">
                            <dt><?= $this->translate('client') ?>:</dt>
                            <dd><?php echo $client->getLabel() ?></dd>
                        </dl>
                        <?php endif ?>

                        <?php  $employer = $project->getContactRelatedByFkContactEmployerId() ?>
                        <?php if (!empty($employer)): ?>
                        <dl class="employer attrib">
                            <dt><?= $this->translate('employer') ?>:</dt>
                            <dd><?php echo $employer->getLabel() ?></dd>
                        </dl>
                        <?php endif ?>
                    </div>

                    <div class="links">
                        <dl class="url attrib">
                            <dt><?= $this->translate('url') ?>:</dt>
                            <dd><a class="extUlr" href="<?= $project->getUrl() ?>" class="more"><?= $project->getUrl() ?></a></dd>
                        </dl>
                    </div>
                </div>
            </section>
        <?php endforeach ?>
        </div>
    </div>
    <?php if (count($pages) > 1): ?>
    <ul class="pagination">
        <?php foreach($pages as $page): ?>
        <li><a href="#<?= $page+1 ?>"><?= $page+1 ?></a></li>
        <?php endforeach ?>
    </ul>
    <?php endif ?>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        SW.projectListAccordion();
    });
</script>