<?= $this->doctype('HTML5') ?>
<html lang="en" class="js no-touch svg inlinesvg svgclippaths no-ie8compat">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Sitework.de - ' . $this->translate('PHP Development'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?= $headLink = $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/gfx/favicon.ico')) ?>
        <?php foreach ($this->assets()->css() as $css) : ?>
            <?php $headLink->appendStylesheet(sprintf('%s/css/%s', $this->basePath(), $css)) ?>
        <?php endforeach ?>
        <?= $headLink ?>
    </head>
    <body>
        <div id="page">
            <header class="contain-to-grid fixed">
                <nav class="top-bar">
                    <ul class="title-area">
                        <li class="name">
                            <h1>
                                <a class="nodeco" href="/">
                                    <span class="title"><?= $this->translate('Sitework.de') ?></span>
                                    <span class="description hide-for-small"><?= $this->translate('PHP Development') ?></span>
                                </a>
                            </h1>
                        </li>
                        <li class="toggle-topbar"><a href="#"><?= $this->translate('Menü') ?></a></li>
                    </ul>
                    <section class="top-bar-section">
                        <?= $this->navigation()->menu(new Zend\Navigation\Navigation($this->navigation('social_navigation')->getPages()))->setUlClass('nav-social hide-for-small right') ?>
                        <?= $this->navigation()->menu(new Zend\Navigation\Navigation($this->navigation('default_navigation')->getPages()))->setUlClass('nav-primary right') ?>
                    </section>
                </nav>
            </header>
            <div id="main" class="row">
                <div id="sidebar" class="large-4 small-12 columns"><?= $this->sidebar ?></div>
                <div id="content" class="large-8 small-12 columns"><?= $this->content ?></div>
            </div>
            <footer>
                <div class="row">
                    <div class="large-6 columns">
                        <span class="copy">&copy; 2007 - 2013, Sitework.de, Matthias Kruschke</span>
                    </div>
                    <div class="large-6 columns">
                        <nav class="bottom-bar"><?= $this->navigation()->menu(new Zend\Navigation\Navigation($this->navigation('footer_navigation')->getPages()))->setUlClass('nav-secondary') ?></nav>
                    </div>
                </div>
            </footer>
        </div>
        <?php $headScript = $this->headScript() ?>
        <?php foreach ($this->assets()->js() as $js) : ?>
            <?php $headScript->appendFile(sprintf('%s/js/%s', $this->basePath(), $js)) ?>
        <?php endforeach ?>
        <?= $headScript ?>
        <script>$(function(){ $(document).foundation(); })</script>
    </body>
</html>
