<div id="sidebarIndex">
    <h2><?= $this->translate('Recent Tweets') ?></h2>
    <?php if (is_array($this->get('twitterCollection')->getTweets())) : ?>
        <ul class="twitterCollection">
        <?php foreach ($this->get('twitterCollection')->getTweets() as $t) : ?>
            <li class="<?= $this->cycle(array('even', 'odd'))->next() ?>">
                <div class="date">
                    <?php $date = new DateTime($t->getCreatedAt(), new DateTimeZone(date_default_timezone_get())) ?>
                    <?= $this->dateFormat($date, IntlDateFormatter::TRADITIONAL, IntlDateFormatter::NONE, Locale::getDefault()) ?>
                </div>
                <div class="text"><?= $t->getText() ?></div>
            </li>
        <?php endforeach ?>
        </ul>
    <?php endif ?>
</div>
