<div id="sidebarIndex">
    <h2><?= $this->translate('Recent Tweets') ?></h2>
    <?php if (is_array($this->get('twitterCollection')->getTweets())) : ?>
        <ul class="twitterCollection">
        <?php foreach ($this->get('twitterCollection')->getTweets() as $t) : ?>
            <li class="<?= $this->cycle(array('even', 'odd'))->next() ?>">
                <div class="date"><?= $t->getCreatedAt() ?></div>
                <div class="text"><?= $t->getText() ?></div>
            </li>
        <?php endforeach ?>
        </ul>
    <?php endif ?>
</div>
