<div id="sidebarContact">
    <h2><?= $this->translate('contact') ?></h2>
    <div class="panel">
        <dl>
            <dt class="panelHeader"><span class="h3"><?= $this->translate('Post address') ?></span></dt>
            <dd class="panelFooter">
                <?= $this->translate('Blücherstr. 37a') ?><br/>
                <?= $this->translate('10961 Berlin') ?><br/>
                <?= $this->translate('Germany') ?>
            </dd>
        </dl>
        <dl>
            <dt class="panelHeader"><span class="h3"><?= $this->translate('Internet') ?></span></dt>
            <dd class="panelSection">
                <span class="label"><?= $this->translate('E-Mail') ?>:</span>
                <span class="value"><?= $this->mailto(array(
                    'address' => 'matthias.kruschke@gmail.com',
                    'text' => $this->translate('Send E-mail'),
                    'encode' => 'hex',
                )) ?>
                </span>
            </dd>
            <dd class="panelSection">
                <span class="label"><?= $this->translate('ICQ') ?>:</span>
                <span class="value">115187074</span>
            </dd>
            <dd class="panelFooter">
                <span class="label"><?= $this->translate('Google') ?>:</span>
                <span class="value">matthias.kruschke</span>
            </dd>
        </dl>
        <dl>
            <dt class="panelHeader"><span class="h3"><?= $this->translate('Tax information') ?></span></dt>
            <dd class="panelSection">
                <span class="label"><?= $this->translate('Tax no.') ?>:</span>
                <span class="value">14/402/61633</span>
            </dd>
            <dd class="panelFooter">
                <span class="label"><?= $this->translate('Tax office') ?>:</span>
                <span class="value"><?= $this->translate('Berlin-Kreuzberg') ?></span>
            </dd>
        </dl>
    </div>
</div>
